{
 "title": "Docker monitoring with node selection",
 "description": "Docker monitoring with Prometheus and cAdvisor with node selection",
 "tags": [ "Monitor Containers" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": true,
 "templating": {
  "list": [
   {
    "name": "container_label_com_docker_compose_service",
    "label": "Name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\",image!=\"\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"})/1024/1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]) * 100)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]) * 100)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\",image!=\"\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_cache{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\",image!=\"\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "I/O Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_fs_read_seconds_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "I/O Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_fs_write_seconds_total{container_label_com_docker_compose_service=~\"$container_label_com_docker_compose_service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}